"""Governance API — manages the full lifecycle of Appeal promotion/rejection,
user approval workflow, and version management.

The GovernanceAPI sits between the Appeal Trial Space (where proposed
modifications live) and the Static Archive (where approved fragments
are stored). It enforces the approval workflow, maintains the genealogical
DAG, provides rollback and version-history capabilities, and aggregates
governance statistics.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple, TYPE_CHECKING

from memory_fragments.config import EvaluatorConfig, GovernanceConfig, default_config
from memory_fragments.models import (
    Appeal,
    AppealMetrics,
    AppealStatus,
    Fragment,
    FragmentMetadata,
    FragmentStatus,
    GenealogyGraph,
)
from memory_fragments.models.appeal import AppealDiff

if TYPE_CHECKING:
    from memory_fragments.archive.static import StaticArchive
    from memory_fragments.archive.appeal_space import AppealTrialSpace
    from memory_fragments.engine.evaluator import Evaluator
    from memory_fragments.engine.diff_explain import DiffExplainEngine


# ---------------------------------------------------------------------------
# GovernanceReport
# ---------------------------------------------------------------------------


@dataclass
class GovernanceReport:
    """A snapshot of an Appeal presented to a human (or automated) reviewer.

    Carries everything needed to make an approve/reject decision: computed
    metrics, a structured diff, a plain‑language explanation, a curated
    list of pros and cons, conflict warnings, provenance information,
    side‑by‑side diff, quality distribution, and model provenance.
    """

    appeal_id: str
    """Unique identifier of the Appeal this report describes."""

    status: AppealStatus
    """Current lifecycle status of the Appeal."""

    sources: List[str]
    """Fragment IDs that were used as input to the Appeal."""

    metrics: AppealMetrics
    """Quantitative metrics computed by the Evaluator (coverage, risk, …)."""

    diff: AppealDiff
    """Structured diff showing what content was added, removed, or modified."""

    explanation: str
    """Human‑readable summary of the diff (generated by DiffExplainEngine)."""

    pros: List[str]
    """Advantages of approving this Appeal (rule‑based or evaluator‑driven)."""

    cons: List[str]
    """Risks or disadvantages of approving this Appeal."""

    proposed_content: str
    """The full proposed fragment content that would be promoted on approval."""

    created_at: str
    """ISO‑8601 timestamp of when the original Appeal was created."""

    # NEW FIELDS — Card 7 enrichment
    conflict_warnings: List[Dict[str, Any]] = field(default_factory=list)
    """Conflict warnings from scanning proposed content against archive."""

    provenance_info: Dict[str, Any] = field(default_factory=dict)
    """Quality provenance for each source fragment."""

    side_by_side_diff: str = ""
    """Side-by-side comparison of source vs. proposed (text block)."""

    source_quality_distribution: str = ""
    """Summary of quality scores across source fragments."""

    model_provenance: Dict[str, Any] = field(default_factory=dict)
    """Model IDs/versions used in the evaluation pipeline."""

    # -- convenience ---------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Serialise the report to a JSON‑compatible dictionary."""
        return {
            "appeal_id": self.appeal_id,
            "status": self.status.value,
            "sources": list(self.sources),
            "metrics": self.metrics.to_dict(),
            "diff": self.diff.to_dict(),
            "explanation": self.explanation,
            "pros": list(self.pros),
            "cons": list(self.cons),
            "proposed_content": self.proposed_content,
            "created_at": self.created_at,
            "conflict_warnings": self.conflict_warnings,
            "provenance_info": self.provenance_info,
            "side_by_side_diff": self.side_by_side_diff,
            "source_quality_distribution": self.source_quality_distribution,
            "model_provenance": self.model_provenance,
        }

    def __repr__(self) -> str:
        return (
            f"GovernanceReport(appeal_id={self.appeal_id!r}, "
            f"status={self.status.value!r}, "
            f"sources={len(self.sources)} source(s), "
            f"pros={len(self.pros)}, cons={len(self.cons)})"
        )


# ---------------------------------------------------------------------------
# GovernanceAPI
# ---------------------------------------------------------------------------


class GovernanceAPI:
    """Coordinates the full Appeal promotion / rejection lifecycle.

    This class is the single entry point for governance operations.  It
    orchestrates the **AppealTrialSpace**, **StaticArchive**, **Evaluator**,
    **DiffExplainEngine**, and **GenealogyGraph** to provide a coherent
    workflow for submitting, reviewing, approving, rejecting, and rolling
    back fragment modifications.
    """

    def __init__(
        self,
        archive: StaticArchive,
        appeal_space: AppealTrialSpace,
        evaluator: Evaluator,
        diff_explain: DiffExplainEngine,
        graph: GenealogyGraph,
        config: GovernanceConfig | None = None,
        quarantine_manager: Optional[Any] = None,
    ) -> None:
        """Initialise the GovernanceAPI.

        Args:
            archive: The **StaticArchive** that stores approved (and
                archived) fragments.
            appeal_space: The **AppealTrialSpace** holding all active
                Appeals.
            evaluator: **Evaluator** used to compute metrics such as
                coverage, risk, and aggregate score.
            diff_explain: **DiffExplainEngine** that produces a
                human‑readable explanation of the changes in an Appeal.
            graph: **GenealogyGraph** tracking the DAG of fragment
                ancestry and provenance.
            config: Override for governance configuration.  Falls back
                to ``default_config.governance`` when ``None``.
            quarantine_manager: Optional **QuarantineManager** reference
                for including quarantine state in governance statistics.
        """
        self._archive = archive
        self._appeal_space = appeal_space
        self._evaluator = evaluator
        self._diff_explain = diff_explain
        self._graph = graph
        self._config = config or default_config.governance
        self._quarantine_manager = quarantine_manager

    # ------------------------------------------------------------------
    # Public workflow API
    # ------------------------------------------------------------------

    def submit_for_review(self, appeal_id: str) -> GovernanceReport:
        """Transition an Appeal into *pending user approval* status.

        After calling this method the Appeal is ready for a human (or
        automated reviewer) to call **approve()** or **reject()**.

        Args:
            appeal_id: Identifier of the Appeal to submit.

        Returns:
            A :class:`GovernanceReport` summarising the Appeal for the
            reviewer.

        Raises:
            ValueError: If *appeal_id* does not exist in the appeal space.
        """
        self._appeal_space.set_status(
            appeal_id, AppealStatus.PENDING_USER_APPROVAL
        )
        return self.get_report(appeal_id)

    def approve(
        self,
        appeal_id: str,
        approver: str = "user",
        notes: str = "",
    ) -> Fragment:
        """Approve a pending Appeal and promote its content to the Static Archive.

        The approval workflow:

        1. Validates the Appeal is in ``PENDING_USER_APPROVAL`` status.
        2. Generates a new, unique fragment ID (``F-XXXX``).
        3. Creates a :class:`Fragment` from the Appeal's proposed content,
           inheriting and merging metadata from source fragments.
        4. Adds the Fragment to the **StaticArchive**.
        5. Records a new node in the **GenealogyGraph** linking the
           promoted fragment to its parents.
        6. Marks the Appeal as ``APPROVED`` and records the resolution
           timestamp.

        Args:
            appeal_id: The Appeal to approve.
            approver: Identifier of the approving entity
                (default ``"user"``).
            notes: Optional human‑readable notes attached to the
                genealogical record.

        Returns:
            The newly created :class:`Fragment`.

        Raises:
            ValueError: If the Appeal does not exist or is not in
                ``PENDING_USER_APPROVAL`` status.
        """
        appeal = self._get_appeal(appeal_id)

        if appeal.status != AppealStatus.PENDING_USER_APPROVAL:
            raise ValueError(
                f"Appeal {appeal_id} cannot be approved in status "
                f"{appeal.status.value!r}; expected "
                f"{AppealStatus.PENDING_USER_APPROVAL.value!r}"
            )

        # -- Create the new Fragment --------------------------------------
        next_id = self._calculate_next_id()
        new_id = f"F-{next_id:04d}"

        source_fragments = self._resolve_source_fragments(appeal.sources)
        merged_metadata = self._merge_metadata(source_fragments, appeal)

        fragment = Fragment(
            fragment_id=new_id,
            content=appeal.proposed_content,
            metadata=merged_metadata,
            parents=list(appeal.sources),
            status=FragmentStatus.ACTIVE,
        )
        self._archive.add_fragment(fragment)

        # -- Gather provenance info from source fragments ------------------
        model_id = ""
        model_version = ""
        quality_source = ""
        provenance_snapshot = ""

        for sf in source_fragments:
            if sf.metadata.provenance is not None:
                model_id = sf.metadata.provenance.final_source.value
                quality_source = sf.metadata.provenance.final_source.value
                provenance_snapshot = json.dumps(
                    sf.metadata.provenance.to_dict(), default=str
                )
                break  # Use first available provenance

        # If no provenance found, record that it's a user-approved governance promotion
        if not quality_source:
            quality_source = "governance_promotion"

        # Record the evaluator model used
        evaluator_model_id = (
            self._evaluator.config.embedding_model
            if hasattr(self._evaluator, "config")
            else ""
        )

        # -- Record in the Genealogy DAG ----------------------------------
        self._graph.add_node(
            fragment_id=new_id,
            parent_ids=list(appeal.sources),
            appeal_id=appeal_id,
            approver=approver,
            checksum=fragment.checksum,
            notes=notes,
            model_id=model_id,
            model_version=model_version,
            evaluator_model_id=evaluator_model_id,
            quality_source=quality_source,
            provenance_snapshot=provenance_snapshot,
        )

        # -- Finalise the Appeal ------------------------------------------
        self._appeal_space.set_status(appeal_id, AppealStatus.APPROVED)

        return fragment

    def reject(self, appeal_id: str, reason: str = "") -> bool:
        """Reject a pending Appeal.

        The Appeal is marked ``REJECTED`` and its resolution timestamp
        is recorded.  If *reason* is provided it replaces (or fills in
        for) the Appeal's existing explanation.

        Args:
            appeal_id: The Appeal to reject.
            reason: Optional explanation for the rejection.

        Returns:
            ``True`` on success.

        Raises:
            ValueError: If *appeal_id* does not exist.
        """
        if reason:
            appeal = self._get_appeal(appeal_id)
            appeal.explanation = reason
            self._appeal_space.update(appeal)
        self._appeal_space.set_status(appeal_id, AppealStatus.REJECTED)
        return True

    def get_report(self, appeal_id: str) -> GovernanceReport | None:
        """Build a comprehensive :class:`GovernanceReport` for an Appeal.

        Gathers the current appeal state, fresh evaluator metrics, a
        diff explanation, and a rule‑based list of pros and cons.

        Enriched with: conflict warnings against the archive, provenance
        info for each source fragment, a side‑by‑side diff, quality
        distribution, and model provenance.

        Args:
            appeal_id: The Appeal to report on.

        Returns:
            A :class:`GovernanceReport`, or ``None`` if *appeal_id* does
            not exist.
        """
        appeal = self._appeal_space.get(appeal_id)
        if appeal is None:
            return None

        # Compute fresh metrics and explanation
        source_fragments = self._resolve_source_fragments(appeal.sources)
        fresh_metrics = self._evaluator.evaluate(appeal, source_fragments)
        appeal.metrics = fresh_metrics

        explanation = self._diff_explain.generate_explanation(
            appeal, source_fragments, fresh_metrics
        )

        pros, cons = self._compute_pros_cons(appeal)

        # --- NEW: Conflict detection ---
        conflict_warnings = self._detect_conflicts(appeal, source_fragments)

        # --- NEW: Conflict-aware pros/cons ---
        if conflict_warnings:
            cons.append(
                f"Conflict detected with {len(conflict_warnings)} "
                f"existing fragment(s)"
            )

        # --- NEW: Provenance info ---
        provenance_info = self._gather_provenance(source_fragments)

        # --- NEW: Side-by-side diff ---
        side_by_side_diff = self._generate_side_by_side(appeal, source_fragments)

        # --- NEW: Quality distribution ---
        source_quality_distribution = self._summarize_quality(source_fragments)

        # --- NEW: Model provenance ---
        model_provenance = self._gather_model_provenance(source_fragments)

        return GovernanceReport(
            appeal_id=appeal.appeal_id,
            status=appeal.status,
            sources=list(appeal.sources),
            metrics=fresh_metrics,
            diff=appeal.diff,
            explanation=explanation,
            pros=pros,
            cons=cons,
            proposed_content=appeal.proposed_content,
            created_at=appeal.created_at.isoformat(),
            conflict_warnings=conflict_warnings,
            provenance_info=provenance_info,
            side_by_side_diff=side_by_side_diff,
            source_quality_distribution=source_quality_distribution,
            model_provenance=model_provenance,
        )

    def get_reports_for_fragment(self, fragment_id: str) -> List[GovernanceReport]:
        """Return all governance reports where *fragment_id* appears as a source.

        Args:
            fragment_id: The fragment to search for in reports.

        Returns:
            List of GovernanceReport objects where the fragment is a source.
        """
        reports: List[GovernanceReport] = []
        for appeal in self._appeal_space.list():
            if fragment_id in appeal.sources:
                report = self.get_report(appeal.appeal_id)
                if report is not None:
                    reports.append(report)
        return reports

    # ------------------------------------------------------------------
    # Version history & rollback
    # ------------------------------------------------------------------

    def get_version_history(self, fragment_id: str) -> Dict[str, Any]:
        """Return genealogical information for a promoted fragment.

        Args:
            fragment_id: The fragment to query.

        Returns:
            A dictionary containing **ancestors**, **descendants**,
            **depth**, **parent_ids**, **child_ids**, and provenance
            metadata (appeal_id, approver, checksum).  Returns an empty
            dict if the fragment is unknown to the genealogy graph.
        """
        node = self._graph.get_node(fragment_id)
        if node is None:
            return {}

        ancestors = self._graph.get_ancestors(fragment_id)
        descendants = self._graph.get_descendants(fragment_id)

        return {
            "fragment_id": fragment_id,
            "depth": node.depth,
            "ancestors": [n.fragment_id for n in ancestors],
            "descendants": [n.fragment_id for n in descendants],
            "parent_ids": list(node.parent_ids),
            "child_ids": list(node.child_ids),
            "appeal_id": node.appeal_id,
            "approver": node.approver,
            "checksum": node.checksum,
            "promotion_notes": node.promotion_notes,
            "timestamp": node.timestamp.isoformat(),
            "roots": [n.fragment_id for n in self._graph.get_roots()],
            "leaves": [n.fragment_id for n in self._graph.get_leaves()],
        }

    def rollback(self, fragment_id: str) -> Fragment | None:
        """Soft‑delete a fragment and return its previous version.

        The fragment is archived (status set to ``ARCHIVED``).  The
        **most recent parent** from the genealogy DAG is returned as
        the "previous version".

        Only works when the fragment exists in the genealogy graph AND
        has at least one parent.

        Args:
            fragment_id: The fragment to roll back.

        Returns:
            The parent :class:`Fragment` (the previous version), or
            ``None`` if the fragment has no parents, is unknown in the
            graph, or is not found in the archive.
        """
        node = self._graph.get_node(fragment_id)
        if node is None or not node.parent_ids:
            return None

        fragment = self._archive.get_fragment(fragment_id)
        if fragment is None:
            return None

        # Soft-delete in-place (the archive stores a reference)
        self._archive.delete(fragment_id)

        # Return the highest-quality parent from the genealogy graph
        best_parent_id = self._select_best_parent(node)
        return self._archive.get_fragment(best_parent_id) if best_parent_id else None

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------

    def get_statistics(self) -> Dict[str, Any]:
        """Return aggregate governance statistics.

        Computed across **all** Appeals currently known to the appeal
        space.

        Returns:
            A dictionary with the following keys:

            - **total_appeals** — total number of Appeals.
            - **approved** — count of approved Appeals.
            - **rejected** — count of rejected Appeals.
            - **pending** — count of Appeals awaiting user approval.
            - **draft** — count of Appeals still in draft status.
            - **expired** — count of expired Appeals.
            - **avg_time_to_decision_seconds** — mean time (seconds)
              from creation to resolution for resolved Appeals.
            - **avg_time_to_decision_formatted** — same duration in a
              human‑readable form (e.g. ``"2h 15m 30s"``).
        """
        appeals = self._appeal_space.list()
        total = len(appeals)

        approved = sum(1 for a in appeals if a.status == AppealStatus.APPROVED)
        rejected = sum(1 for a in appeals if a.status == AppealStatus.REJECTED)
        pending = sum(
            1 for a in appeals if a.status == AppealStatus.PENDING_USER_APPROVAL
        )
        draft = sum(1 for a in appeals if a.status == AppealStatus.DRAFT)
        expired = sum(1 for a in appeals if a.status == AppealStatus.EXPIRED)

        # Average decision time (seconds) for resolved Appeals
        decision_times: List[float] = []
        for a in appeals:
            if a.resolved_at is not None and a.created_at is not None:
                delta = (a.resolved_at - a.created_at).total_seconds()
                if delta >= 0:
                    decision_times.append(delta)

        avg_time_s: float = (
            sum(decision_times) / len(decision_times) if decision_times else 0.0
        )

        # Quarantine info
        if self._quarantine_manager is not None:
            from memory_fragments.library.quarantine import QuarantineManager

            quarantine_size = self._quarantine_manager.count()
            unresolved = len(self._quarantine_manager.list_unresolved())
            pending_notifications = len(
                self._quarantine_manager.get_pending_notifications()
            )
        else:
            quarantine_size = 0
            unresolved = 0
            pending_notifications = 0

        return {
            "total_appeals": total,
            "approved": approved,
            "rejected": rejected,
            "pending": pending,
            "draft": draft,
            "expired": expired,
            "avg_time_to_decision_seconds": round(avg_time_s, 2),
            "avg_time_to_decision_formatted": self._format_duration(avg_time_s),
            "quarantine_size": quarantine_size,
            "quarantine": {
                "size": quarantine_size,
                "unresolved": unresolved,
                "pending_notifications": pending_notifications,
            },
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_appeal(self, appeal_id: str) -> Appeal:
        """Retrieve an Appeal from the space, or raise a descriptive error."""
        appeal = self._appeal_space.get(appeal_id)
        if appeal is None:
            raise ValueError(
                f"Appeal {appeal_id!r} does not exist in the appeal space."
            )
        return appeal

    def _calculate_next_id(self) -> int:
        """Scan the archive for the highest ``F-XXXX`` ID and return ``max + 1``.

        The first call when the archive is empty returns ``1`` (producing
        ``F-0001``).
        """
        max_id = 0
        for fid in self._archive.all_fragment_ids():
            match = re.match(r"F-(\d+)", fid)
            if match:
                num = int(match.group(1))
                if num > max_id:
                    max_id = num
        return max_id + 1

    def _select_best_parent(self, node: GenealogyNode) -> Optional[str]:
        """Select the best parent fragment from a node's parent list.

        Picks the parent with the highest quality score. Quality scores are
        read from the archive's stored fragments (since GenealogyNode doesn't
        store quality directly).

        Args:
            node: The genealogy node whose parents to evaluate.

        Returns:
            The parent_id with highest quality, or the last parent if none found
            (fallback to original behavior).
        """
        if not node.parent_ids:
            return None

        best_id = node.parent_ids[-1]  # Default fallback
        best_quality = -1.0

        for pid in node.parent_ids:
            frag = self._archive.get_fragment(pid)
            if frag is not None and frag.metadata.quality > best_quality:
                best_quality = frag.metadata.quality
                best_id = pid

        return best_id

    def _resolve_source_fragments(
        self, source_ids: List[str]
    ) -> List[Fragment]:
        """Resolve source fragment IDs to :class:`Fragment` objects.

        Silently skips IDs that no longer exist in the archive.
        """
        fragments: List[Fragment] = []
        for sid in source_ids:
            frag = self._archive.get_fragment(sid)
            if frag is not None:
                fragments.append(frag)
        return fragments

    def _merge_metadata(
        self,
        source_fragments: List[Fragment],
        appeal: Appeal,
    ) -> FragmentMetadata:
        """Merge metadata from source fragments into a single metadata block.

        * Topics are deduplicated and joined with ``" | "``.
        * Tags are unioned and sorted.
        * Quality scores are averaged.
        * Authors are concatenated.

        When there are no source fragments the appeal's explanation
        (truncated) is used as the topic.
        """
        topics: set[str] = set()
        tags: set[str] = set()
        quality_sum = 0.0
        authors: set[str] = set()

        for frag in source_fragments:
            if frag.metadata.topic:
                topics.add(frag.metadata.topic)
            tags.update(frag.metadata.tags)
            quality_sum += frag.metadata.quality
            if frag.metadata.author:
                authors.add(frag.metadata.author)

        count = len(source_fragments) or 1

        return FragmentMetadata(
            topic=" | ".join(sorted(topics))
            if topics
            else appeal.explanation[:60],
            tags=sorted(tags),
            quality=round(quality_sum / count, 4),
            author=", ".join(sorted(authors)) if authors else "system",
            source="governance:approve",
        )

    def _compute_pros_cons(
        self, appeal: Appeal
    ) -> Tuple[List[str], List[str]]:
        """Derive pros and cons from the Appeal's metrics and diff.

        This is a rule‑based heuristic.  Subclasses may override to
        integrate LLM‑generated or evaluator‑provided assessments.
        """
        pros: List[str] = []
        cons: List[str] = []

        metrics = appeal.metrics
        risk_threshold = default_config.evaluator.risk_threshold

        # -- Coverage ----------------------------------------------------
        if metrics.coverage >= 0.7:
            pros.append(
                f"High coverage ({metrics.coverage:.0%}) of source material"
            )
        elif metrics.coverage <= 0.3:
            cons.append(
                f"Low coverage ({metrics.coverage:.0%}) of source material"
            )

        # -- Risk --------------------------------------------------------
        if metrics.risk < risk_threshold:
            pros.append(f"Low risk score ({metrics.risk:.2f})")
        elif metrics.risk > 0.6:
            cons.append(f"Elevated risk score ({metrics.risk:.2f})")

        # -- Token delta -------------------------------------------------
        delta = metrics.delta_token
        if delta > 0:
            pros.append(f"Adds {delta} new tokens of information")
        elif delta < 0:
            pros.append(f"Reduces token count by {abs(delta)} tokens")

        # -- Aggregate score ---------------------------------------------
        if metrics.aggregate_score >= 0.7:
            pros.append(
                f"Strong aggregate score ({metrics.aggregate_score:.2f})"
            )
        elif metrics.aggregate_score <= 0.3:
            cons.append(
                f"Low aggregate score ({metrics.aggregate_score:.2f})"
            )

        # -- Diff indicators ---------------------------------------------
        if appeal.diff.added:
            pros.append(f"Adds {len(appeal.diff.added)} new passage(s)")
        if appeal.diff.removed:
            cons.append(
                f"Removes {len(appeal.diff.removed)} existing passage(s)"
            )

        # -- Fallbacks so the lists are never empty ----------------------
        if not pros:
            pros.append("No significant advantages identified")
        if not cons:
            cons.append("No significant concerns identified")

        return pros, cons

    # ------------------------------------------------------------------
    # Enriched report helpers (Card 7)
    # ------------------------------------------------------------------

    def _detect_conflicts(
        self,
        appeal: Appeal,
        source_fragments: List[Fragment],
    ) -> List[Dict[str, Any]]:
        """Check if proposed content conflicts with existing archive fragments.

        Uses ConflictDetector to scan the proposed content against all
        archive fragments not in the source list.

        Args:
            appeal: The Appeal whose proposed content is checked.
            source_fragments: Source fragments of the Appeal (excluded
                from conflict scanning).

        Returns:
            List of conflict warning dicts, each with *other_fragment_id*,
            *similarity*, *contradiction_score*, *detection_method*, and
            *overlap_excerpt*.
        """
        from memory_fragments.engine.conflict import ConflictDetector

        all_fragments = self._archive.list_all()
        source_ids = {f.fragment_id for f in source_fragments}
        other_fragments = [
            f for f in all_fragments if f.fragment_id not in source_ids
        ]

        if not other_fragments:
            return []

        # Create a temporary fragment for conflict scanning
        temp_fragment = Fragment(
            fragment_id=f"__proposed_{appeal.appeal_id}",
            content=appeal.proposed_content,
        )

        detector = ConflictDetector()
        report = detector.scan_fragment(temp_fragment, other_fragments)

        warnings: List[Dict[str, Any]] = []
        for entry in report.conflicts:
            warnings.append({
                "other_fragment_id": entry.other_fragment_id,
                "similarity": entry.similarity,
                "contradiction_score": entry.contradiction_score,
                "detection_method": entry.detection_method,
                "overlap_excerpt": entry.overlap_excerpt,
            })

        return warnings

    def _gather_provenance(
        self,
        source_fragments: List[Fragment],
    ) -> Dict[str, Any]:
        """Gather quality provenance info from source fragments.

        Args:
            source_fragments: Source fragments to extract provenance from.

        Returns:
            A dict with *sources* (keyed by fragment ID) and *summary*
            (count, min/max/mean quality, quality sources).
        """
        provenance_info: Dict[str, Any] = {
            "sources": {},
            "summary": {},
        }

        qualities: List[float] = []
        sources_used: set[str] = set()

        for frag in source_fragments:
            fid = frag.fragment_id
            entry: Dict[str, Any] = {
                "quality": frag.metadata.quality,
            }

            if frag.metadata.provenance is not None:
                entry["provenance"] = {
                    "final_source": frag.metadata.provenance.final_source.value,
                    "final_quality": frag.metadata.provenance.final_quality,
                    "evaluation_count": len(
                        frag.metadata.provenance.evaluations
                    ),
                    "consensus_method": (
                        frag.metadata.provenance.consensus_method
                    ),
                }
                sources_used.add(
                    frag.metadata.provenance.final_source.value
                )
            else:
                entry["provenance"] = None

            provenance_info["sources"][fid] = entry
            qualities.append(frag.metadata.quality)

        if qualities:
            provenance_info["summary"] = {
                "count": len(qualities),
                "min_quality": round(min(qualities), 4),
                "max_quality": round(max(qualities), 4),
                "mean_quality": round(
                    sum(qualities) / len(qualities), 4
                ),
                "quality_sources": sorted(list(sources_used)),
            }

        return provenance_info

    def _generate_side_by_side(
        self,
        appeal: Appeal,
        source_fragments: List[Fragment],
    ) -> str:
        """Generate a side-by-side comparison using difflib.

        Shows the source text vs proposed text with line numbers for
        changed lines.  Truncated to 2000 characters to keep reports
        manageable.

        Args:
            appeal: The Appeal with proposed content.
            source_fragments: Source fragments compared against.

        Returns:
            Unified diff text (truncated to 2000 chars).
        """
        import difflib

        source_text = "\n".join(f.content for f in source_fragments)
        proposed_text = appeal.proposed_content

        source_lines = source_text.splitlines()
        proposed_lines = proposed_text.splitlines()

        udiff = difflib.unified_diff(
            source_lines,
            proposed_lines,
            fromfile="original_sources",
            tofile="proposed_content",
            lineterm="",
        )
        text_diff = "\n".join(udiff)

        # Truncate to avoid massive reports
        return text_diff[:2000]

    def _summarize_quality(
        self,
        source_fragments: List[Fragment],
    ) -> str:
        """Create a textual summary of quality distribution across sources.

        Args:
            source_fragments: Source fragments to summarise.

        Returns:
            A multi-line string with fragment count, quality range, mean
            quality, and provenance source counts.
        """
        if not source_fragments:
            return "No source fragments available."

        qualities = [f.metadata.quality for f in source_fragments]
        provenance_counts: Dict[str, int] = {}
        for f in source_fragments:
            if f.metadata.provenance is not None:
                src = f.metadata.provenance.final_source.value
                provenance_counts[src] = provenance_counts.get(src, 0) + 1
            else:
                provenance_counts["unknown"] = (
                    provenance_counts.get("unknown", 0) + 1
                )

        lines = [
            f"Source fragments: {len(source_fragments)}",
            f"Quality range: {min(qualities):.2f} - {max(qualities):.2f}",
            f"Mean quality: {sum(qualities) / len(qualities):.3f}",
            f"Quality sources: {provenance_counts}",
        ]
        return "\n".join(lines)

    def _gather_model_provenance(
        self,
        source_fragments: List[Fragment],
    ) -> Dict[str, Any]:
        """Gather model versioning info from source fragments and evaluator.

        Args:
            source_fragments: Source fragments to query model info for.

        Returns:
            A dict with *evaluator* model info and *source_fragments*
            model versioning details.
        """
        models: Dict[str, Any] = {
            "evaluator": {
                "embedding_model": getattr(
                    self._evaluator.config, "embedding_model", "unknown"
                ),
            },
            "source_fragments": {},
        }

        for frag in source_fragments:
            node = self._graph.get_node(frag.fragment_id)
            if node is not None and node.model_id:
                models["source_fragments"][frag.fragment_id] = {
                    "model_id": node.model_id,
                    "model_version": node.model_version,
                    "evaluator_model_id": node.evaluator_model_id,
                    "quality_source": node.quality_source,
                }

        return models

    @staticmethod
    def _format_duration(total_seconds: float) -> str:
        """Format a duration in seconds to a friendly string like ``"2h 15m 30s"``."""
        if total_seconds < 0:
            return "0s"
        if total_seconds < 60:
            return f"{total_seconds:.0f}s"
        minutes, secs = divmod(int(total_seconds), 60)
        if minutes < 60:
            return f"{minutes}m {secs}s"
        hours, mins = divmod(minutes, 60)
        return f"{hours}h {mins}m {secs}s"
